spin_manifest_version = 2

[application]
name = "topcloud"
version = "0.2.0"
authors = ["blah28722 <blah28722@gmail.com>"]
description = "A Fermyon Cloud application"

[[trigger.http]]
route = "/..."
component = "topcloud"

[component.topcloud]
source = "target/wasm32-wasi/release/topcloud.wasm"
allowed_outbound_hosts = [ "https://random-data-api.fermyon.app" ]
[component.topcloud.build]
command = "cargo build --target wasm32-wasi --release"
