spin_manifest_version = 2

[application]
name = "top_cloud"
version = "0.2.0"
authors = ["blah28722 <blah28722@gmail.com>"]
description = "A Fermyon Cloud application"

[[trigger.http]]
route = "/..."
component = "topcloud"

[component.cloudstart]
source = "target/wasm32-wasi/release/top_cloud.wasm"
[component.cloudstart.build]
command = "cargo build --target wasm32-wasi --release"
